version: '3'
services:
    moa:
        user: $UID:$GID
        build:
            context: .
            args:
                UID: $UID
                GID: $GID
                UNAME: $UNAME
        volumes:
            - ./kaggle:/kaggle
        ports:
            - 8000:8000
