# ex_name: classifier
ex_name: normal
# ex_name: test

# preprocess:
#     kwargs:
#         g_n_comp: 50
#         c_n_comp: 15
#         threshold: 0.5
#     function_name: gene_cell_split_pca_use_row_drop_low_variace 
preprocess:
    kwargs:
        n_comp: 50
        threshold: 0.7
        is_rankgauss: false
    # function_name: select_features_gen_cell_concat_ica_drop_low_variace
    function_name: select_features

train:
    num_folds: 5
    num_ensemble: 2
    is_under: false
    is_lda: false
    mode: classifier
    # classifier params
    params:
        objective: binary
        colsample_bytree: 0.3
        boosting_type: gbdt
        learning_rate: 0.01
        metric: binary_logloss
        random_seed: 1234
        max_depth: 5
        num_leaves: 24
        verbose: -1
