ex_name: classifier

# preprocess:
#     kwargs:
#         g_n_comp: 50
#         c_n_comp: 15
#         threshold: 0.5
#     function_name: gene_cell_split_pca_use_row_drop_low_variace 
preprocess:
    kwargs:
        n_comp: 50
        threshold: 0.7
    function_name: select_features

train:
    num_folds: 5
    num_ensemble: 2
    is_under: true
    params:
        n_estimators: 200
        objective: binary
        colsample_bytree: 0.3
        metrics: auc
        boosting_type: gbdt
        learning_rate: 0.01
        random_state: 1234
        # metric: binary_logloss
        # random_seed: 1234
        # device: gpu
        # gpu_use_dp: False
        # max_depth: 5
        # max_depth: -1
        # force_col_wise: true
        # num_leaves: 24
        # max_bin: 63
        # max_bin: 15
