
version: '3'
services:
    moa-gpu:
        runtime: nvidia
        user: $UID:$GID
        build:
            context: .
            args:
                UID: $UID
                GID: $GID
                UNAME: $UNAME
        volumes:
            - ../kaggle:/kaggle
            - ../gbdt:/gbdt
        ports:
            - 8000:8000
        command: python /gbdt/src/main.py
