ex_name: nn

preprocess:
    kwargs:
        n_comp: 50
        threshold: 0.7
        is_rankgauss: true
    function_name: select_features_gen_cell_concat_ica_drop_low_variace_add_features
    # function_name: select_features

train:
    # num_folds: 5
    # num_ensemble: 1
    is_under: true
    is_lda: true
    mode: normal
    batch_size: 512
    num_hidden_layers: 3
    hidden_size: 32
    dropout_rate: 0.5
    epochs: 25
    device: cuda
    learning_rate: 1e-3
